// Generated by CoffeeScript 1.9.3
(function() {
  var DATA, DATA_TEMP, EVALS, HEADERS, ID, bigTable, copyToClipboard, toggleEval;

  HEADERS = ['ID', 'Classe', 'Nom', 'Prénom', 'D1-1.1', 'D1-1.2', 'D1-1.3', 'D1-1.4', 'D1-1.5', 'D1-3.1', 'D1-3.2', 'D1-3.3', 'D1-3.4', 'D1-3.5', 'D1-3.6', 'D1-3.7', 'D2.1', 'D2.2', 'D2.3', 'D2.4', 'D3.1', 'D3.2', 'D3.3', 'D3.4', 'D4.1', 'D4.2', 'D5.1'];

  DATA = [HEADERS];

  EVALS = {
    "D1-1": {
      "name": "Composante 1",
      "subtitle": "Comprendre, s’exprimer en utilisant la langue française à l’oral et à l’écrit",
      "significants": {
        "S’exprimer à l’oral": ["Être capable d’une prise de parole continue d’une durée variable selon les types de  discours (de cinq à dix minutes au maximum, si le propos croise narration, description, opinion et argumentation; moins s’il s’agit d’une seule de ces composantes), avec quelques relances de la part du professeur si nécessaire;", "Pouvoir exprimer une impression, un avis, une opinion de manière raisonnée, en respectant les formes d’un oral codifié et socialisé;", "Savoir faire preuve d’une relative liberté dans sa prise de parole par rapport à ses notes de préparation."],
        "Comprendre des énoncés oraux": ["Reformuler le sens général d’un discours oral découvert de manière autonome et adapté par ses références et son niveau de langue aux connaissances définies par les programmes", "Rendre compte de la teneur générale de discours oraux complexes (conversations, débats)."],
        "Lire et comprendre l’écrit": ["Proposer sa compréhension d’un texte inconnu d’environ trente lignes ou d’un document associant image et énoncé écrit, en s’appuyant sur des éléments d’analyse précis et en mobilisant ses connaissances linguistiques et culturelles ;", "Proposer un compte rendu de ce qu’il retient de la lecture d’une œuvre et la mise en évidence de l’essentiel d’un texte long."],
        "Écrire": ["Être capable de réponses écrites développées et argumentées à des questions de compréhension et d’analyse d’un texte et/ou d’une image;", "Savoir écrire un texte pouvant aller jusqu’à 2000 à 3000 signes dans une langue globalement correcte, en cohérence avec les attendus en étude de la langue, et suffisamment riche pour lui permettre de produire un texte d’invention, intéressant et conforme à l’énoncé de l’exercice, ou d’exprimer sa pensée de manière  argumentée et nuancée;", "Produire un texte rédigé dans une langue suffisamment maîtrisée pour que son intelligibilité ne soit pas compromise;", "Réinvestir le vocabulaire spécialisé à bon escient."],
        "Exploiter les ressources de la langue": ["Réfléchir sur le système linguistique", "Mobiliser les connaissances et procédures orthographiques et syntaxiques étudiées pour produire un texte pouvant aller jusqu’à 2000 à 3000 signes dans une langue globalement correcte;", "Réviser un énoncé produit par lui-même ou un autre scripteur à partir d’indications orientant cette révision;", "Savoir analyser en contexte des unités lexicales en les mettant en relation et en se fondant sur l’analyse de leur forme;", "Savoir analyser les propriétés d’un ou de plusieurs éléments linguistiques en les référant au système de la langue et en les comparant éventuellement au système d’une autre langue."]
      }
    },
    "D1-3": {
      "nom": "Composante 3",
      "subtitle": "Comprendre, s’exprimer en utilisant les langages mathématiques, scientifiques et informatiques ",
      "significants": {
        "Utiliser les nombres": ["Comprendre et utiliser les notions de divisibilité et de nombre premier.", "Effectuer (mentalement, à la main, à la calculatrice, à l’aide d’un tableur) des calculs engageant les quatre opérations et des comparaisons sur des nombres rationnels positifs ou négatifs.", "Effectuer des calculs numériques impliquant des puissances.", "Passer d’une écriture d’un nombre à une autre (écritures décimale et fractionnaire, notation scientifique, pourcentages).", "Comprendre et utiliser la notion de racine carrée.", "Repérer un nombre sur une droite graduée.", "Reconnaître et résoudre une situation de proportionnalité."],
        "Utiliser le calcul littéral": ["Développer et factoriser des expressions littérales dans des cas très simples.", "Citer et utiliser une expression littérale, notamment pour exprimer une grandeur en fonction d’autres grandeurs.", "Produire une expression littérale.", "Dans une expression littérale, substituer une lettre par une valeur numérique, en utilisant si nécessaire les unités adaptées.", "Mettre un problème simple en équation.", "Résoudre des équations ou des inéquations du premier degré."],
        "Exprimer une grandeur mesurée ou calculée dans une unité adaptée": ["Accompagner de son unité toute valeur numérique d’une grandeur physique mesurée, calculée ou fournie.", "Utiliser, dans les calculs numériques, un système d’unités cohérent."],
        "Passer d’un langage à un autre": ["Passer du langage courant à un langage scientifique ou technique et vice versa.", "Passer d’un registre de représentation à un autre (tableau, graphique, croquis, symbole, schéma, etc.).", "Exploiter, dans des situations simples, les différences (complémentarité, redondance, complexité, etc.) entre différents registres de représentation"],
        "Utiliser le langage des probabilités": ["Utiliser le vocabulaire lié aux notions élémentaires de probabilités : - calculer des probabilités dans un contexte simple; - faire le lien entre fréquence et probabilité; - simuler une expérience aléatoire."],
        "Utiliser et produire des représentations d’objets": ["Utiliser et produire des figures géométriques.", "Lire des plans et des cartes.", "Se repérer sur des cartes à différentes échelles.", "Utiliser le langage cartographique pour réaliser une production graphique.", "Comprendre l’effet de quelques transformations (déplacements, agrandissements-réductions) sur des grandeurs géométriques.", "Se repérer sur une droite graduée, dans le plan muni d’un repère orthogonal, dans un parallélépipède rectangle, sur une sphère.", "Utiliser et produire des représentations de solides.", "Lire, interpréter et produire des tableaux, des graphiques, des diagrammes.", "Utiliser des indicateurs statistiques."],
        "Utiliser l’algorithmique et la programmation pour créer des applications simples": ["Expliquer le déroulement et le résultat produit par un algorithme simple.", "Écrire un algorithme ou un programme qui permet une interaction avec l’utilisateur ou entre les objets qu’il utilise, en réponse à un problème donné.", "Mettre au point un programme pour corriger une erreur ou apporter une amélioration.", "Implanter et tester un programme dans un système réel pour imposer un comportement."]
      }
    },
    "D2": {
      "name": "Domaine 2",
      "subtitle": "Les méthodes et outils pour apprendre",
      "significants": {
        "Organiser son travail personnel": ["Choisir et utiliser différents outils et techniques pour garder la trace de ses activités et/ou recherches et permettre un entraînement au travers d’un travail personnel.", "Planifier les étapes et les tâches pour la réalisation d’une production."],
        "Coopérer et réaliser des projets": ["Définir et respecter une organisation et un partage des tâches dans le cadre d’un travail de groupe."],
        "Rechercher et traiter l’information et s’initier aux langages des médias": ["Rechercher des informations dans différents médias (presse écrite, audiovisuelle, web) et ressources documentaires.", "Apprécier la fiabilité des informations recueillies en croisant différentes sources."],
        "Mobiliser des outils numériques pour apprendre, échanger, communiquer": ["Utiliser des outils numériques pour réaliser une production (scientifique, artistique, motrice, expérimentale, document multimédia…).", "Utiliser des outils numériques pour analyser des données ou une production (orale, artistique, motrice, technologique, etc.).", "Utiliser des outils et espaces numériques pour échanger, stocker, mutualiser des informations."]
      }
    },
    "D3": {
      "name": "Domaine 3",
      "subtitle": "La formation de la personne et du citoyen",
      "significants": {
        "Maîtriser l’expression de sa sensibilité et de ses opinions, respecter celles des autres": ["Expliciter les émotions ressenties.", "Formuler une opinion, prendre de la distance avec celle-ci, la confronter à celle d’autrui et en discuter."],
        "Connaître et comprendre la règle et le droit": ["S’approprier et respecter les règles de fonctionnement de son établissement et de collectifs plus restreints, et participer à leur élaboration.", "Connaître, comprendre et analyser les principes, les valeurs et les symboles de la République française et des sociétés démocratiques."],
        "Exercer son esprit critique, faire preuve de réflexion et de discernement": ["Rendre compte des argumentaires développés par différents protagonistes relativement à une thématique.", "Utiliser les médias et l’information de manière responsable et raisonnée.", "Distinguer ce qui relève d’une croyance ou d’une opinion et ce qui constitue un savoir (ou un fait) scientifique.", "Distinguer la perception subjective de l’analyse objective."],
        "Faire preuve de responsabilité, respecter les règles de la vie collective, s’engager et prendre des initiatives": ["Assumer des responsabilités et prendre des initiatives dans l’établissement et/ou dans la classe.", "S’impliquer dans la mise en place d’un événement dans l’établissement."]
      }
    },
    "D4": {
      "name": "Domaine 4",
      "subtitle": "Systèmes naturels et systèmes techniques",
      "significants": {
        "Mener une démarche scientifique, résoudre un problème": ["Extraire, organiser les informations utiles et les transcrire dans un langage adapté.", "Mettre en œuvre un raisonnement logique simple."],
        "Mener une démarche scientifique, résoudre un problème": ["Modéliser et représenter des phénomènes et des objets.", "Mettre en œuvre un protocole expérimental, réaliser le prototype d’un objet.", "Pratiquer le calcul numérique (exact et approché) et le calcul littéral.", "Contrôler la vraisemblance d’un résultat.", "Communiquer sur ses démarches, ses résultats et ses choix, en argumentant"],
        "Concevoir des objets et systèmes techniques": ["Concevoir des objets simples, des éléments de programme informatique, des protocoles biotechnologiques en réponse à un besoin."]
      }
    },
    "D5": {
      "name": "Domaine 5",
      "subtitle": "Représentation du monde",
      "significants": {
        "Situer et se situer dans le temps et l’espace": ["Maîtriser de manière autonome des repères dans le temps :<br> - connaître et localiser dans le temps de grandes périodes historiques, des phénomènes historiques, des faits et des événements, des mouvements intellectuels, artistiques et culturels;<br> - situer et ordonner des faits dans le temps ; pratiquer de conscients allers-retours dans la chronologie, maîtriser la chronologie narrative, savoir ordonner un récit.", "Maîtriser de manière autonome des repères dans l’espace :<br> - connaître et localiser des repères spatiaux aux différentes échelles et sur des projections cartographiques variées ;<br> - se repérer et repérer des lieux dans l’espace en utilisant des plans, des cartes et des outils de géolocalisation ;<br> - situer et mettre en relation des lieux et des espaces à partir de cartes d’échelles et de projection variées et d’images.", "Contextualiser un document, un texte, une œuvre, un(e) artiste, un personnage, une découverte scientifique, un fait artistique ou une notion dans le temps et dans une ou plusieurs aires géographiques et culturelles."]
      }
    }
  };

  ID = 1;

  DATA_TEMP = [];

  bigTable = function(data) {
    var arrayToTable, color, defaults, head, i, j, options, row, rows, table, tfoot, thead, val;
    arrayToTable = function(data, options) {};
    'use strict';
    table = $('<table id="tableau"/>');
    rows = [];
    defaults = {
      th: true,
      thead: false,
      tfoot: false,
      attrs: {}
    };
    options = $.extend(defaults, options);
    table.attr(options.attrs);
    i = 0;
    while (i < data.length) {
      row = $("<tr data-id='" + data[i][0] + "'/>");
      j = 0;
      while (j < data[i].length) {
        if (i === 0 && options.th) {
          head = data[i][j];
          if (j === 0) {
            head = "<input type='checkbox' data-row='" + i + "'>" + head;
          }
          if (j > 3) {
            if (j < 16) {
              head = "<img class='thdomain' src='img/domaine" + data[i][j].slice(1, 4) + ".svg' data-domain='D1-1'><br>" + data[i][j];
            } else {
              head = "<img  class='thdomain' src='img/domaine" + data[i][j][1] + ".svg' data-domain='D1-1'><br>" + data[i][j];
            }
            row.append($("<th data-row='" + i + "' data-col='" + j + "' data-id='" + data[i][j] + "' /th>").html(head));
          } else {
            row.append($("<th data-row='" + i + "' data-col='" + j + "' data-id='" + data[i][j] + "'></th>").html(head));
          }
        } else {
          if (j === 0) {
            val = "<input type='checkbox' data-id='" + data[i][j] + "''><button class='eleve_id' data-id='" + data[i][j] + "''>" + data[i][j] + "</button>";
          } else {
            val = "" + data[i][j];
            color = {
              0: "white",
              10: "red",
              25: "yellow",
              40: "lightGreen",
              50: "green"
            }[val];
          }
          if (color === void 0) {
            color = "white";
          }
          row.append($("<td class='" + color + "' data-row='" + i + "' data-col='" + j + "' data-id='" + data[i][0] + "' data-dom='" + data[0][j] + "'></td>").html(val));
        }
        j = j + 1;
      }
      rows.push(row);
      i = i + 1;
    }
    if (options.thead) {
      thead = rows.shift();
      thead = $('<thead />').append(thead);
      table.append(thead);
    }
    if (options.tfoot) {
      tfoot = rows.pop();
    }
    i = 0;
    while (i < rows.length) {
      table.append(rows[i]);
      i = i + 1;
    }
    if (options.tfoot) {
      tfoot = $('<tfoot />').append(tfoot);
      table.append(tfoot);
    }
    return table;
    return table = arrayToTable(data, {
      thead: true,
      attrs: {
        "class": 'table'
      }
    });
  };

  toggleEval = function(dom) {
    var $cells;
    $cells = $("#scoreTable").find("td:visible[data-dom='" + dom + "']");
    return $cells.each(function() {
      var col, id, row;
      row = $(this).data("row");
      col = $(this).data("col");
      id = $(this).data("id");
      if ($(this).hasClass("white")) {
        $(this).toggleClass("white shaded");
        return $(".significants[data-dom='" + dom + "']").toggleClass("white shaded");
      } else if ($(this).hasClass("shaded")) {
        $(this).toggleClass("shaded red");
        $(".significants[data-dom='" + dom + "']").toggleClass("shaded red");
        if (row !== void 0 && col !== void 0) {
          DATA[id][col] = 10;
          return $(this).html(10);
        }
      } else if ($(this).hasClass("red")) {
        $(this).toggleClass("red yellow");
        $(".significants[data-dom='" + dom + "']").toggleClass("red yellow");
        if (row !== void 0 && col !== void 0) {
          DATA[id][col] = 25;
          return $(this).html(25);
        }
      } else if ($(this).hasClass("yellow")) {
        $(this).toggleClass("yellow lightGreen");
        $(".significants[data-dom='" + dom + "']").toggleClass("yellow lightGreen");
        if (row !== void 0 && col !== void 0) {
          DATA[id][col] = 40;
          return $(this).html(40);
        }
      } else if ($(this).hasClass("lightGreen")) {
        $(this).toggleClass("lightGreen green");
        $(".significants[data-dom='" + dom + "']").toggleClass("lightGreen green");
        if (row !== void 0 && col !== void 0) {
          DATA[id][col] = 50;
          return $(this).html(50);
        }
      } else if ($(this).hasClass("green")) {
        $(this).toggleClass("green white");
        $(".significants[data-dom='" + dom + "']").toggleClass("green white");
        if (row !== void 0 && col !== void 0) {
          DATA[id][col] = 0;
          return $(this).html(0);
        }
      }
    });
  };

  copyToClipboard = function(el) {
    var body, e, range, sel;
    body = document.body;
    if (document.createRange && window.getSelection) {
      range = document.createRange();
      sel = window.getSelection();
      sel.removeAllRanges();
      try {
        range.selectNodeContents(el);
        sel.addRange(range);
      } catch (_error) {
        e = _error;
        range.selectNode(el);
        sel.addRange(range);
      }
    } else if (body.createTextRange) {
      range = body.createTextRange();
      range.moveToElementText(el);
      range.select();
    }
    return document.execCommand("Copy");
  };

  $(function() {
    var $html, $s, $select, evals, i, id, k, l, len, len1, m, n, o, p, ref, ref1, s;
    window.onbeforeunload = function() {
      return "";
    };
    $.getJSON("eleves.json", function(data) {
      var items, l, len, o, results;
      items = [];
      $.each(data, function(o, val) {
        return items.push(val);
      });
      results = [];
      for (l = 0, len = items.length; l < len; l++) {
        o = items[l];
        results.push(DATA.push([o.id, o.classe, o.nom, o.prenom, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]));
      }
      return results;
    });
    $select = $("<select id='level'></select>");
    for (o = l = 3; l <= 6; o = ++l) {
      $select.append("<option value='" + o + "'>" + o + "</option>");
    }
    $("#tabs").before($select);
    $select = $("<select id='letter'></select>");
    ref = " ABCDEFGHIJKLM";
    for (m = 0, len = ref.length; m < len; m++) {
      o = ref[m];
      $select.append("<option value='" + o + "'>" + o + "</option>");
    }
    $("#tabs").before($select);
    evals = Object.keys(EVALS);
    for (k in EVALS) {
      $html = $("<div id=\"" + k + "\" class=\"domain\">\n  <div class=\"nom\">" + k + " : " + EVALS[k]['subtitle'] + "</div>\n</div>    ");
      n = 0;
      for (s in EVALS[k].significants) {
        id = ID++;
        n++;
        $s = $("<div class='significants white' data-dom='" + k + "." + n + "'>" + s + "<img class='more' src='css/icons/more.png' data-id='" + id + "'><div class='info' id='" + id + "' title='" + s + "'><ul></ul></div></div>");
        ref1 = EVALS[k].significants[s];
        for (p = 0, len1 = ref1.length; p < len1; p++) {
          i = ref1[p];
          $s.find(".info ul").append("<li class='item'>" + i + "</li>");
        }
        $html.append($s);
      }
      $("#significants_area").append($html);
    }
    $("#significants_area").draggable();
    $(".info").dialog({
      autoOpen: false,
      width: "auto"
    });
    $(".more").on("click", function(event) {
      event.stopPropagation();
      id = $(this).data("id");
      return $("#" + id).dialog("open");
    });
    $("body").on("click", "input[data-row='0']", function() {
      var checkBoxes;
      checkBoxes = $("input[type='checkbox']").not($(this));
      if ($(this).prop("checked")) {
        checkBoxes.prop("checked", true);
        return checkBoxes.closest("tr").addClass("export");
      } else {
        checkBoxes.prop("checked", false);
        return checkBoxes.closest("tr").removeClass("export");
      }
    });
    $("body").on("click", "input[type='checkbox']", function() {
      var text;
      $(this).closest("tr").toggleClass("export");
      text = "";
      $(".export").each(function() {
        $(this).find("td").each(function() {
          text += $(this).text();
          return text += ",";
        });
        return text += "\n";
      });
      $("#bar").text(text);
      return new Clipboard(".btn");
    });
    $("#letter").change(function() {
      var CLASSE, len2, letter, q, table;
      letter = $("#letter").val();
      if (letter !== " ") {
        CLASSE = $("#level").val() + letter;
        DATA_TEMP = [HEADERS];
        for (q = 0, len2 = DATA.length; q < len2; q++) {
          o = DATA[q];
          if (o[1] === CLASSE) {
            DATA_TEMP.push(o);
          }
        }
      } else {
        DATA_TEMP = DATA;
      }
      table = bigTable(DATA_TEMP);
      return $('#scoreTable').empty().append(table);
    });
    $("body").on("click", "button.eleve_id", function() {
      id = $(this).data("id");
      $("tr").hide();
      $("tr:first, tr[data-id='" + id + "']").show();
      $(".significants").removeClass("white red yellow lightGreen green");
      return $("td[data-id='" + id + "']").each(function() {
        var col, dom, val;
        col = $(this).data("col");
        dom = $(this).data("dom");
        val = DATA[id][col];
        switch (val) {
          case 0:
            if ($(this).hasClass("shaded")) {
              return $(".significants[data-dom='" + dom + "']").addClass("shaded");
            } else {
              return $(".significants[data-dom='" + dom + "']").addClass("white");
            }
            break;
          case 10:
            return $(".significants[data-dom='" + dom + "']").addClass("red");
          case 25:
            return $(".significants[data-dom='" + dom + "']").addClass("yellow");
          case 40:
            return $(".significants[data-dom='" + dom + "']").addClass("lightGreen");
          case 50:
            return $(".significants[data-dom='" + dom + "']").addClass("green");
        }
      });
    });
    $(".tabdomain").addClass("show");
    $(".tabdomain[data-domain='all']").hide();
    $(".tabdomain[data-domain='none']").on("click", function() {
      $("#significants_area").hide();
      $(".tabdomain[data-domain='all']").show();
      $(this).hide();
      return $("tr").show();
    });
    $(".tabdomain[data-domain='all']").on("click", function() {
      $("#significants_area").show();
      $(".tabdomain[data-domain='none']").show();
      return $(this).hide();
    });
    $(".tabdomain").on("click", function(event) {
      var dom;
      dom = $(this).data("domain");
      if (dom !== "all" && dom !== "none") {
        $(this).toggleClass("show hide");
        return $("#" + dom).toggle();
      }
    });
    return $(".significants").on("click", function() {
      return toggleEval($(this).data("dom"));
    });
  });

}).call(this);
